# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: moh-hcim
canonical: http://moh.fhir/bc-clientregistry
name: BCHCIM
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
title: BC Client Registry FHIR 0 Guide

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Overview: overview.html
  Design: 
     Summary: design.html
     Search Patient: search.html
     Revise And Merge Patient: reviseAndMerge.html
     Distributions: distributions.html
     Identifiers: identifiers.html
  V3 Transition: v3Transition.html
  Connected Partner: connectedPartner.html
  Artifacts: artifacts.html
  Future Plans: futurePlans.html
  Glossary: terminology.html
  Credits: credits.html

pages:
  index.md:
    title: Introduction
  overview.md:
    title: HCIM Overview
  v3Transition.md:
    title: Transition from V3 Provider to FHIR
  design.md:
    title: FHIR Design
  connectedPartner.md:
    title: Connected Partners
  terminology.md:
    title: Glossary
  credits.md:
    title: Credits
  search.md:
    title: Search Patient
  reviseAndMerge.md:
    title: Revise and Merge Patient
  distributions.md:
    title: Distribute Patient
  futurePlans.md:
    title: Future Plans
  identifiers.md:
    title: Identifiers

groups:
   Patient:
      name: Patient
      description: 0 associated with Patients
      resources:
         - StructureDefinition/bc-patient
   Operations:
      name: Operations
      description: The defined Operations
      resources:
         - OperationDefinition/bc-patient-find-candidates
         - OperationDefinition/bc-patient-get-demographics
         - OperationDefinition/bc-patient-revise
         - OperationDefinition/bc-patient-revise-newborn
         - OperationDefinition/bc-patient-merge
   OperationParameters:
      name: OperationParameters
      description: The parameter profiles associated with the Client Registry Operations
      resources:
         - StructureDefinition/bc-metadata-parameters
         - StructureDefinition/bc-patient-business-parameters
   OperationRequestExamples:
      name: OperationRequestExamples
      description: A set of operation request examples
      resources:
         - Parameters/FindCandidates
         - Parameters/FindCandidates-SSRI
         - Parameters/FindCandidates-MomsPHN
         - Parameters/GetDemographics
         - Parameters/RevisePatient-UpdateExisting
         - Parameters/RevisePatient-New
         - Parameters/RevisePatient-Newborn
         - Parameters/MergePatient-TwoID
   OperationResponseExamples:
      name: OperationResponseExamples
      description: A set of operation response examples
      resources:
         - Bundle/FindCandidatesResponse
         - Bundle/GetDemographicsResponse
         - StructureDefinition/bc-search-response-bundle
         - StructureDefinition/bc-revise-and-merge-response-bundle 

