id: fhir.ca-bc.client
canonical: http://hlth.gov.bc.ca/fhir/client
name: BCHealthClientIdentityManagement
title: BC Client Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Client Registry
status: active
version: 1.0.0
fhirVersion: 4.0.1

dependencies:
  hl7.fhir.ca.baseline: 1.1.7
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0

copyrightYear: 2022+
releaseLabel: Build CI
jurisdiction: urn:iso:std:iso:3166#CA "Canada"
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health

menu:
  Overview: index.html
  Design: 
     Summary: design.html
     Search Patient Operations: search.html
     Add, Revise, Update And Merge Patient: reviseAndMerge.html
     Identifiers: identifiers.html
     Data Absent: absentData.html
     RESTful Services: restful.html
  V3 Transition: v3Transition.html
  Connected Partner: connectedPartner.html
  Capability Statement: capabilityStatement.html
  Artifacts: artifacts.html
  Future Plans: futurePlans.html
  Glossary: terminology.html
  Credits: credits.html

pages:
  index.md:
    title: Client Registry Overview  
  design.md:
    title: FHIR Design
  search.md:
    title: Search Patient Operations
  reviseAndMerge.md:
    title: Add, Revise and Merge Patient
  identifiers.md:
    title: Identifiers
  absentData.md:
    title: Data Absent Reason
  restful.md:
    title: RESTful Services
  v3Transition.md:
    title: Transition from V3 Provider to FHIR
  connectedPartner.md:
    title: Connected Partners
  capabilityStatement.md:
    title: Capability Statement
  futurePlans.md:
    title: Future Plans
  terminology.md:
    title: Glossary
  credits.md:
    title: Credits


groups:
   CapabilityStatement:
      name: Capability Statement
      description: The Capability Statement for Client Registry
      resources:
         - CapabilityStatement/bc-hcim-capability-statement-server
         - CapabilityStatement/bc-hcim-capability-statement-client
   Operations:
      name: Operation Definitions
      description: The defined Operations
      resources:
         - OperationDefinition/bc-patient-find-candidates
         - OperationDefinition/bc-patient-get-demographics
         - OperationDefinition/bc-patient-add
         - OperationDefinition/bc-patient-revise
         - OperationDefinition/bc-patient-merge
        #  - OperationDefinition/bc-patient-history
   PatientProfile:
      name: Patient Profile
      description: The BC Patient profile
      resources:
         - StructureDefinition/bc-patient
         - StructureDefinition/bc-merge-patient
   Bundles:
      name: Supporting Profiles - Bundles
      description: Bundles that support Patient and Client Registry Operations - Request and Response
      resources:
         - StructureDefinition/bc-find-candidates-request-bundle
         - StructureDefinition/bc-get-demographics-request-bundle
         - StructureDefinition/bc-search-response-bundle
         - StructureDefinition/bc-add-request-bundle 
         - StructureDefinition/bc-add-response-bundle 
        # - StructureDefinition/bc-merge-request-bundle 
        # - StructureDefinition/bc-merge-response-bundle 
         - StructureDefinition/bc-revise-request-bundle 
         - StructureDefinition/bc-revise-response-bundle 
         - StructureDefinition/bc-async-ack-response-bundle
   SupportingProfiles:
      name: Supporting Profiles
      description: Artifacts associated with resources that support Patient and Client Registry Operations
      resources: 
         - StructureDefinition/bc-metadata-parameters-in
         - StructureDefinition/bc-metadata-parameters-out
         - StructureDefinition/bc-metadata-parameter-async-response
   RequestExamples:
      name: Request Examples
      description: A set of operation request examples
      resources:
         - Bundle/GetDemographics-Request
         - Bundle/GetDemographics-withHistory-Request
         - Bundle/GetDemographics-Request-By-SSRI
         - Bundle/FindCandidates-Request
         - Bundle/FindNewbornByMumsPHN-Request
         - Bundle/AddPatient-Request
         - Bundle/AddNewbornByMumsPHN-Request
        # - Bundle/Merge-Only-Request
        # - Bundle/Merge-SSRI-Request
        # - Bundle/Merge-WithPayload-Request
         - Parameters/Merge-Request
         - Parameters/Merge-Min-Request
         - Bundle/Revise-withMaxData-Request
         - Bundle/Revise-Request-No-SRI
   ResponseExamples:
      name: Response Examples
      description: A set of operation response examples
      resources:
         - Bundle/GetDemographics-Response
         - Bundle/GetDemographics-withHistory-Response
         - Bundle/GetDemographics-withPHNInfo-Response
         - Bundle/GetDemographics-Response-Masked
         - Bundle/FindCandidates-Response
         - Bundle/FindNewbornByMumsPHN-Response
         - Bundle/AddPatient-Response
         - Parameters/Merge-Response
        # - Bundle/Merge-WithPayload-Response
         - Bundle/Revise-Response
         - Bundle/Revise-Async-ACK
   RestfulExamples:
      name: RESTful Examples
      description: A set of RESTful request examples
      resources:
         - Patient/Force-Create-Request
         - Patient/Newborn-Request
         - Patient/Revise-Request-No-SRI-RESTful
         - Patient/Revise-Request

parameters:
  special-url:
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/CodeSystem/bc-client-registry-address-validation-code-system
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/CodeSystem/bc-client-registry-merge-status-code-system
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/CodeSystem/bc-client-registry-patient-change-notification-events
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/CodeSystem/bc-client-registry-update-patient-operation-code-system
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/CodeSystem/bc-identifier-status-code-system
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/CodeSystem/bc-operation-outcome-details-code-system
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-address-validation-value-set
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-client-registry-patient-change-notification-events
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-client-registry-update-patient-operation-value-set
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-contact-point-system-value-set
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-contact-point-use-value-set
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-identifier-status-value-set
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-merge-status-value-set
    - https://terminology.hlth.gov.bc.ca/ClientRegistry/ValueSet/bc-name-use-value-set
    