id: fhir.ca-bc.client
canonical: http://hl7.org/fhir/ca-bc/client
name: BCHealthClientIdentityManagement
title: BC Client Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Client Registry
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health
  jurisdiction: urn:iso:std:iso:3166#CA "Canada"

menu:
  Home: index.html
  Overview: overview.html
  Design: 
     Summary: design.html
     Search Patient: search.html
     Revise And Merge Patient: reviseAndMerge.html
     Distributions: distributions.html
     Identifiers: identifiers.html
  V3 Transition: v3Transition.html
  Connected Partner: connectedPartner.html
  Artifacts: artifacts.html
  Future Plans: futurePlans.html
  Glossary: terminology.html
  Credits: credits.html

pages:
  index.md:
    title: Introduction
  overview.md:
    title: HCIM Overview
  v3Transition.md:
    title: Transition from V3 Provider to FHIR
  design.md:
    title: FHIR Design
  connectedPartner.md:
    title: Connected Partners
  terminology.md:
    title: Glossary
  credits.md:
    title: Credits
  search.md:
    title: Search Patient
  reviseAndMerge.md:
    title: Revise and Merge Patient
  distributions.md:
    title: Distribute Patient
  futurePlans.md:
    title: Future Plans
  identifiers.md:
    title: Identifiers

groups:
   Patient Profile:
      name: PatientProfile
      description: The BC Patient profile
      resources:
         - StructureDefinition/bc-patient
   Supporting Profiles:
      name: Profiles
      description: Artifacts associated with resources that support Patient and Client Registry Operations
      resources:
         - StructureDefinition/bc-search-response-bundle
         - StructureDefinition/bc-revise-response-bundle 
         - StructureDefinition/bc-merge-response-bundle 
         - StructureDefinition/bc-metadata-parameters
         - StructureDefinition/bc-patient-business-parameters
   Operations:
      name: OperationsDefinitions
      description: The defined Operations
      resources:
         - OperationDefinition/bc-patient-find-candidates
         - OperationDefinition/bc-patient-get-demographics
         - OperationDefinition/bc-patient-revise
         - OperationDefinition/bc-patient-revise-newborn
         - OperationDefinition/bc-patient-merge
   RequestExamples:
      name: RequestExamples
      description: A set of operation request examples
      resources:
         - Parameters/FindCandidates
         - Parameters/FindCandidates-UsingSSRI
         - Parameters/FindCandidates-UsingMomsPHN
         - Parameters/GetDemographics
         - Parameters/RevisePatient-UpdateExisting
         - Parameters/RevisePatient-New
         - Parameters/RevisePatient-Newborn
         - Parameters/MergePatient-TwoNonSurvivors
   ResponseExamples:
      name: ResponseExamples
      description: A set of operation response examples
      resources:
         - Bundle/FindCandidatesResponse
         - Bundle/GetDemographicsResponse
         - Bundle/RevisePatientResponse
         - Bundle/MergePatientResponse

