id: fhir.ca-bc.client
canonical: http://hlth.gov.bc.ca/fhir/client
name: BCHealthClientIdentityManagement
title: BC Client Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Client Registry
status: draft
version: 1.0.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.ca.baseline: 1.1.4
  hl7.fhir.uv.subscriptions-backport: 1.1.0
copyrightYear: 2022+
releaseLabel: Build CI
jurisdiction: urn:iso:std:iso:3166#CA "Canada"
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health

menu:
  Home: index.html
  Overview: overview.html
  Design: 
     Summary: design.html
     Search Patient: search.html
     Add, Revise, Update And Merge Patient: reviseAndMerge.html
     Patient Change Notifications: distributions.html
     Identifiers: identifiers.html
     Data Absent: absentData.html
  V3 Transition: v3Transition.html
  Connected Partner: connectedPartner.html
  Capability Statement: capabilityStatement.html
  Artifacts: artifacts.html
  Future Plans: futurePlans.html
  Glossary: terminology.html
  Credits: credits.html

pages:
  index.md:
    title: Introduction
  overview.md:
    title: HCIM Overview
  v3Transition.md:
    title: Transition from V3 Provider to FHIR
  design.md:
    title: FHIR Design
  connectedPartner.md:
    title: Connected Partners
  terminology.md:
    title: Glossary
  credits.md:
    title: Credits
  search.md:
    title: Search Patient
  reviseAndMerge.md:
    title: Add, Revise and Merge Patient
  distributions.md:
    title: Patient Change Notification
  futurePlans.md:
    title: Future Plans
  identifiers.md:
    title: Identifiers
  absentData.md:
    title: Data Absent Reason
  capabilityStatement.md:
    title: Capability Statement

groups:
   CapabilityStatement:
      name: Capability Statement
      description: The Capability Statement for Client Registry
      resources:
         - CapabilityStatement/bc-hcim-capability-statement-server
         - CapabilityStatement/bc-hcim-capability-statement-client
   Operations:
      name: Operation Definitions
      description: The defined Operations
      resources:
         - OperationDefinition/bc-patient-find-candidates
         - OperationDefinition/bc-patient-get-demographics
         - OperationDefinition/bc-patient-get-demographics-withEligibility
         - OperationDefinition/bc-patient-add
         - OperationDefinition/bc-patient-revise
         - OperationDefinition/bc-patient-update
         - OperationDefinition/bc-patient-merge
         - OperationDefinition/bc-patient-notification
         - OperationDefinition/bc-patient-update
         - OperationDefinition/bc-patient-history
   PatientProfile:
      name: Patient Profile
      description: The BC Patient profile
      resources:
         - StructureDefinition/bc-patient
         - StructureDefinition/bc-merge-patient
         - StructureDefinition/bc-update-patient
         #- StructureDefinition/bc-patient-by-example
   SupportingProfiles:
      name: Supporting Profiles
      description: Artifacts associated with resources that support Patient and Client Registry Operations
      resources:
         - StructureDefinition/bc-find-candidates-request-bundle
         - StructureDefinition/bc-get-demographics-request-bundle
         - StructureDefinition/bc-search-response-bundle
         - StructureDefinition/bc-search-withEligibility-response-bundle
         - StructureDefinition/bc-add-request-bundle 
         - StructureDefinition/bc-add-response-bundle 
         - StructureDefinition/bc-merge-request-bundle 
         - StructureDefinition/bc-merge-response-bundle 
         - StructureDefinition/bc-revise-request-bundle 
         - StructureDefinition/bc-revise-response-bundle 
         - StructureDefinition/bc-update-request-bundle 
         - StructureDefinition/bc-metadata-parameters-in
         - StructureDefinition/bc-metadata-parameters-out
         - StructureDefinition/bc-async-ack-response-bundle
         - StructureDefinition/bc-metadata-parameter-async-response
   RequestExamples:
      name: Request Examples
      description: A set of operation request examples
      resources:
         - Bundle/GetDemographics-Request
         - Bundle/GetDemographics-withHistory-Request
         - Bundle/FindCandidates-Request
         - Bundle/FindNewbornByMumsPHN-Request
         - Bundle/AddPatient-Request
         - Bundle/AddNewbornByMumsPHN-Request
         - Bundle/Merge-Only-Request
         - Bundle/Merge-SSRI-Request
         - Bundle/Merge-WithPayload-Request
         - Bundle/Revise-withMaxData-Request

         #- Bundle/Bundle-FindCandidatesByExample-Request-Example
         #- Bundle/Bundle-FindCandidates-UsingMomsPHN-Request-Example
         #- Bundle/Bundle-GetDemographics-Request-Example
         #- Bundle/Bundle-AddPatient-Request-Example
         #- Bundle/Bundle-MergePatient-Request-Example
         #- Bundle/Bundle-RevisePatient-Request-Example
         #- Bundle/Bundle-AddPatient-Newborn-Request-Example
   ResponseExamples:
      name: Response Examples
      description: A set of operation response examples
      resources:
         - Bundle/GetDemographics-Response
         - Bundle/GetDemographics-withHistory-Response
         - Bundle/GetDemographics-withPHNInfo-Response
         - Bundle/FindCandidates-Response
         - Bundle/FindNewbornByMumsPHN-Response
         - Bundle/AddPatient-Response
         - Bundle/Merge-Response
         - Bundle/Merge-WithPayload-Response
         - Bundle/Revise-Response
         - Bundle/Revise-Async-ACK

         #- Bundle/Bundle-FindCandidates-Response-Example
         #- Bundle/Bundle-FindCandidates-Response-MomsPHN-Example
         #- Bundle/Bundle-GetDemographics-Response-Example
         #- Bundle/Bundle-GetDemographicsWithEligibility-Response-Example
         #- Bundle/Bundle-AddPatient-Response-Example
         #- Bundle/Bundle-RevisePatient-Response-Example
         #- Bundle/Bundle-UpdatePatient-Response-Example
         #- Bundle/Bundle-MergePatient-Response-Example*/
