id: fhir.ca-bc.client
canonical: http://hlth.gov.bc.ca/fhir/client
name: BCHealthClientIdentityManagement
title: BC Client Registry FHIR Implementation Guide
description: FHIR Implementation Guide for BC MOH Client Registry
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Build CI
jurisdiction: urn:iso:std:iso:3166#CA "Canada"
publisher:
  name: BC Ministry of Health
  url: https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health

menu:
  Home: index.html
  Overview: overview.html
  Design: 
     Summary: design.html
     Search Patient: search.html
     Add, Revise And Merge Patient: reviseAndMerge.html
     Patient Change Notificaitons: distributions.html
     Identifiers: identifiers.html
  V3 Transition: v3Transition.html
  Connected Partner: connectedPartner.html
  Capability Statement: capabilityStatement.html
  Artifacts: artifacts.html
  Future Plans: futurePlans.html
  Glossary: terminology.html
  Credits: credits.html

pages:
  index.md:
    title: Introduction
  overview.md:
    title: HCIM Overview
  v3Transition.md:
    title: Transition from V3 Provider to FHIR
  design.md:
    title: FHIR Design
  connectedPartner.md:
    title: Connected Partners
  terminology.md:
    title: Glossary
  credits.md:
    title: Credits
  search.md:
    title: Search Patient
  reviseAndMerge.md:
    title: Revise and Merge Patient
  distributions.md:
    title: Patient Change Notification
  futurePlans.md:
    title: Future Plans
  identifiers.md:
    title: Identifiers
  capabilityStatement.md:
    title: Capability Statement

groups:
   CapabilityStatement:
      name: Capability Statement
      description: The Capability Statement for Client Registry
      resources:
         - CapabilityStatement/bc-hcim-capability-statement-server
         - CapabilityStatement/bc-hcim-capability-statement-client
   PatientProfile:
      name: Patient Profile
      description: The BC Patient profile
      resources:
         - StructureDefinition/bc-patient
   SupportingProfiles:
      name: Supporting Profiles
      description: Artifacts associated with resources that support Patient and Client Registry Operations
      resources:
         - StructureDefinition/bc-search-response-bundle
         - StructureDefinition/bc-search-withEligibility-response-bundle
         - StructureDefinition/bc-add-response-bundle 
         - StructureDefinition/bc-revise-response-bundle 
         - StructureDefinition/bc-partial-revise-response-bundle 
         - StructureDefinition/bc-merge-response-bundle 
         - StructureDefinition/bc-metadata-parameters
         - StructureDefinition/bc-patient-business-parameters
   Operations:
      name: Operation Definitions
      description: The defined Operations
      resources:
         - OperationDefinition/bc-patient-find-candidates
         - OperationDefinition/bc-patient-get-demographics
         - OperationDefinition/bc-patient-get-demographics-withEligibility
         - OperationDefinition/bc-patient-add
         - OperationDefinition/bc-patient-revise
         - OperationDefinition/bc-patient-partial-revise
         - OperationDefinition/bc-patient-merge
         - OperationDefinition/bc-patient-notification
   RequestExamples:
      name: Request Examples
      description: A set of operation request examples
      resources:
         - Parameters/Parameters-FindCandidates-Example
         - Parameters/Parameters-FindCandidates-UsingMomsPHN-Example
         - Parameters/Parameters-GetDemographics-Example
         - Parameters/Parameters-GetDemographicsWithEligibility-Example
         - Parameters/Parameters-RevisePatient-Example
         - Parameters/Parameters-PartialRevisePatient-Example
         - Parameters/Parameters-AddPatient-Example
         - Parameters/Parameters-AddPatient-Newborn-Example
         - Parameters/Parameters-MergePatient-TwoNonSurvivors-Example
   ResponseExamples:
      name: Response Examples
      description: A set of operation response examples
      resources:
         - Bundle/Bundle-FindCandidates-Response-Example
         - Bundle/Bundle-FindCandidates-Response-MomsPHN-Example
         - Bundle/Bundle-GetDemographics-Response-Example
         - Bundle/Bundle-GetDemographicsWithEligibility-Response-Example
         - Bundle/Bundle-AddPatient-Response-Example
         - Bundle/Bundle-RevisePatient-Response-Example
         - Bundle/Bundle-PartialRevisePatient-Response-Example
         - Bundle/Bundle-MergePatient-Response-Example

